---
title: "ploty_testing"
author: "Saund"
date: "20/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(plotly)
```

Their original code
```{r original code, eval=FALSE}
fig <- w.ws[j:k]%>%plot_ly(x=~Date,type='candlestick',open=~us10y.Open,high=~us10y.High,low=~us10y.Low,close=~us10y.Settle)
figs <- us10y.p$cwc$f.d5.w[j:k]%>%plot_ly(x=w.ws[j:k,Date],y=~us10y.f.d5.suw,type='scatter',mode='lines+markers')
figp <- us10y.p$cwc$f.d5.w[j:k]%>%plot_ly(x=w.ws[j:k,Date],y=~us10y.f.d5.prw,type='scatter',mode='lines+markers')
figs10 <- us10y.p$cwc$f.d10.w[j:k]%>%plot_ly(x=w.ws[j:k,Date],y=~us10y.f.d10.suw,type='scatter',mode='lines+markers')
figp10 <- us10y.p$cwc$f.d10.w[j:k]%>%plot_ly(x=w.ws[j:k,Date],y=~us10y.f.d10.prw,type='scatter',mode='lines+markers')
figf <- subplot(fig,figs,figp,figs10,figp10,nrows=5,shareX=TRUE)%>%layout(xaxis=list(rangeslider=list(visible=F)))

l <- list(
type='line',x0='2020-04-24', 
x1 = '2020-05-18',
y0=0.579,
y1=0.739,
xref='x',yref='y',
line=list(color='green',width=0.5))

layout(figf,shapes=l)%>%
config(edits = list(shapePosition = TRUE))
```


load data 
```{r loading}
  load('w.ws.RData')
  j <- 3
  k <- 10000

  
  #output$info <- renderText({
  #  paste0("x=", input$plot_click$x, "\ny=", input$plot_click$y)
  #})
  
  fig <- w.ws[j:k] %>%
    plot_ly(x=~Date,
            type='candlestick',
            open=~Open,
            high=~High,
            low=~Low,
            close=~Settle) 
  
  figs <- us10y.p$cwc$f.d5.w[j:k] %>%
    plot_ly(x=w.ws[j:k,Date],
            y=~us10y.f.d5.suw,
            type='scatter',
            mode='lines+markers')
  figp <- us10y.p$cwc$f.d5.w[j:k]  %>%
    plot_ly(x=w.ws[j:k,Date],
            y=~us10y.f.d5.prw,
            type='scatter',
            mode='lines+markers')
  figs10 <- us10y.p$cwc$f.d10.w[j:k]  %>%
    plot_ly(x=w.ws[j:k,Date],
            y=~us10y.f.d10.suw,
            type='scatter',
            mode='lines+markers')
  figp10 <- us10y.p$cwc$f.d10.w[j:k]  %>%
    plot_ly(x=w.ws[j:k,Date],
            y=~us10y.f.d10.prw,type='scatter',
            mode='lines+markers')
  figf <- subplot(fig,figs,figp,figs10,figp10,
                  nrows=5,
                  shareX=TRUE) %>%
          layout(xaxis=list(rangeslider=list(visible=F)))

  l <- list(
    list(
    type='line',
    x0='2016-04-24', 
    x1 = '2020-05-18',
    y0=0.579,
    y1=4.739,
    xref='x',
    yref='y',
    line=list(color='green',width=0.5)),
  list(
    type='line',
    x0='2016-04-24', 
    x1 = '2020-05-18',
    y0=0.879,
    y1=0.739,
    xref='x',
    yref='y',
    line=list(color='green',width=0.5))
  )
  
l1 = list(    
  type='line',
    x0='2016-04-24', 
    x1 = '2020-05-18',
    y0=0.879,
    y1=0.739,
    xref='x',
    yref='y',
    line=list(color='green',width=0.5)
)
l2 = list(
    type='line',
    x0='2016-04-24', 
    x1 = '2020-05-18',
    y0=0.579,
    y1=4.739,
    xref='x',
    yref='y',
    line=list(color='green',width=0.5)
  )

line <- list(
  type = "line",
  line = list(color = "pink"),
  xref = "x",
  yref = "y"
)

l1x = list(
    type='line',
    x='2016-04-24', 
    xend = '2020-05-18',
    y=0.579,
    yend=4.739,
    xref='x',
    yref='y',
    line=list(color='green',width=0.5)
  )

l2x = list(
    type='line',
    x='2016-04-24', 
    xend = '2020-05-18',
    y=0.579,
    yend=4.739,
    xref='x',
    yref='y',
    line=list(color='green',width=0.5)
  )

lines <- list()
for (i in c(0, 3, 5, 7, 9, 13)) {
  line[["x0"]] <- i
  line[["x1"]] <- i + 2
  line[c("y0", "y1")] <- sin(i + 1)
  lines <- c(lines, list(line))
}

vline <- function(color = "red") {
  list(
    type = "line", 
    y0 = 2, 
    y1 = 4, 
    yref = "paper",
    x0 = '2016-04-24', 
    x1 = '2020-05-18', 
    line = list(color = color)
  )
}

hline <- function(color = "blue") {
  list(
    type = "line", 
    x0 = '2016-04-24', 
    x1 = '2020-05-18', 
    xref = "paper",
    y0 = 5, 
    y1 = 2, 
    line = list(color = color)
  )
}
lines_data <- data.frame(x0=c('2016-04-24', '2016-04-24'), x1=c('2018-04-24', '2018-04-24'), y0=c(2,5), y1=c(3,2), xref=c('x','x'), yref=c('y','y'), type=c("line", "line"))

a <- list(
  x = lines_data$x0,
  y = lines_data$y0,
  text = "annotation a",
  xref = "x",
  yref = "y",
  ax = 20,
  ay = -40
)

# initiate a line shape object
line <- list(
  type = "line",
  line = list(color = "pink"),
  xref = "x",
  yref = "y"
)

lines <- list()
for (i in c(1, 2)) {
  line[["x0"]] <- lines_data$x0[i]
  line[["x1"]] <- lines_data$x1[i]
  line[["y0"]] <- lines_data$y0[i]
  line[["y1"]] <- lines_data$y1[i]
  lines <- c(lines, list(line))
}

l1 <- list(
  type='line',
  x0 = lines_data$x0[2], 
  x1 = lines_data$x1[2],
  y0 = lines_data$y0[2],
  y1 = lines_data$y1[2],
  xref='x',yref='y',
  line=list(color='red',width=0.5))

l2 <- list(
  type='line',
  x0 = lines_data$x0[1], 
  x1 = lines_data$x1[1],
  y0 = lines_data$y0[1],
  y1 = lines_data$y1[1],
  xref='x',yref='y',
  line=list(color='green',width=0.5))

l3 <- list(
  type='line',
  x0 = lines_data$x0[1], 
  x1 = lines_data$x1[1],
  y0 = lines_data$y0[2],
  y1 = lines_data$y1[1],
  xref='x',yref='y',
  line=list(color='blue',width=0.5))

i <- length(lines)+1
lines[[i]] <- list(
  type='line',
  x0 = lines_data$x0[1], 
  x1 = lines_data$x1[1],
  y0 = lines_data$y0[2],
  y1 = lines_data$y1[1],
  xref='x',yref='y',
  line=list(color='blue',width=0.5))


lines=list(l1,l2)

t <- layout(fig, title = 'changing?? with Lines', shapes=lines)
t

fig <- w.ws[j:k] %>%
  plot_ly(x=~Date,
          type='candlestick',
          open=~Open,
          high=~High,
          low=~Low,
          close=~Settle)
  
layout(figf) %>%
  config(edits = list(shapePosition = TRUE)) 

```
